config {
  type: "incremental",
  schema: "BQ_PFU_INCIPY",
  name: "atenea_historico",

  bigquery: {
    partitionBy: "execution_date"
  }
}

pre_operations {

DELETE FROM ${self()}

WHERE execution_date <
      DATE_SUB(
        CURRENT_DATE(),
        INTERVAL 3 YEAR
      ) OR execution_date = CURRENT_DATE();

}


SELECT
CURRENT_DATE() AS execution_date,
CURRENT_TIMESTAMP() AS execution_timestamp,
ld_createdon,
apd_es_matricula
FROM ${ref("Atenea")}