config {
  type: "table",
  schema: "BQ_PFU_INCIPY"
}

SELECT 
l.* EXCEPT(lead_day, lead_month, lead_year),
f.* EXCEPT(user_pseudo_id, first_visit_ts),
DATE_DIFF(DATE(TIMESTAMP_MICROS(purchase_timestamp)), DATE(TIMESTAMP_MICROS(first_visit_ts)), DAY) AS days_since_first_visit
 FROM ${ref("atenea_purchases")} l
 LEFT JOIN ${ref("features_train")} f
 ON l.user_pseudo_id = f.user_pseudo_id
 WHERE product_id is not null and transaction_id is not null and l.user_pseudo_id is not null